### ISSUE TITLE
0.3-1 not working

### ISSUE THREAD

**Issue by eson57** [theyosh/WiFiKilL3r#2]
0.3-1 not working on any of my Jolla devices (J1, JC). App is stuck on "Loading..." and I can't add trusted network. What can I do to debug?

**Comment by theyosh** [comment]
Thanks for this bug. Forgot to create the home folders where the data is being stored. An update is in the openrepos warehouse.

**Comment by eson57** [comment]
Sorry, but the problem is still there. I also tried a complete reinstall.
Can't save trusted network and can't activate KilL3r.

**Comment by theyosh** [comment]
Ok, then we need to manually figure this out. I hope that you know how to SSH to your phone with user nemo.
1. Is there a folder at location: `/home/nemo/.WiFiKilL3r` (hidden folder)
2. If so, which files are inside?
3. Are the following files at the following locations: `/home/nemo/.local/share/systemd/user/WiFiKilL3r.service` and `/home/nemo/.local/share/systemd/user/WiFiKilL3r.timer`
4. The pythons script should be located at:
   `/usr/share/WiFiKilL3r/qml/python/WiFiKilL3r.py`

I am not sure if my systemd setup is standard. Could be that you don't have the folders for systemd

**Comment by eson57** [comment]
- 1. /home/nemo/.WiFiKilL3r is missing
- 3. /home/nemo/.local/share/systemd/user/ is there but no WiFiKilL3r.service or WiFiKilL3r.timer
- 4. pythons script are present

**Comment by theyosh** [comment]
Hm, missing the WiFiKilL3r folder is probably a result of a python code issue. I try to determent the nemo user home folder. Could be that is not working somehow.

Could you try the following as root! (devel-su):
edit file `/usr/share/WiFiKilL3r/qml/python/WiFiKilL3r.py`
and change `HOME_FOLDER = os.path.expanduser('~')` to `HOME_FOLDER = '/home/nemo'`

That should also to the trick for the systemd files.

Then just start my app as normal, and see if the .WiFiKilL3r folder is created. And also the systemd files are copied

**Comment by theyosh** [comment]
Or could it be, that in the /root/ folder is a .WiFiKilL3r folder? Then you are running the apps as root?

**Comment by eson57** [comment]
Nope, didn't work. No .WiFiKilL3r, WiFiKilL3r.service or WiFiKilL3r.timer... and no .WiFiKilL3r in root.

**Comment by eson57** [comment]
I'm running openVPN but that shouldn't affect should it? I noticed openvpn.service in systemd.
I did try to disable vpn with no change.

**Comment by theyosh** [comment]
Ok, this will be harder to fix then expected. Last thing I can think of is running manually, but that will shutdown your wifi, because you don't have valid networks yet.

Try as nemo user:
`python3 /usr/share/WiFiKilL3r/qml/python/WiFiKilL3r.py -d 1 -a run_check`
It should at least produce some output

**Comment by eson57** [comment]
```
[root@Sailfish nemo]# python3 /usr/share/WiFiKilL3r/qml/python/WiFiKilL3r.py -d 1 -a run_check
Traceback (most recent call last):
  File "/usr/share/WiFiKilL3r/qml/python/WiFiKilL3r.py", line 3, in <module>
    import dbus
ImportError: No module named 'dbus'
```

Seems something is missing...

**Comment by eson57** [comment]
Sorry, I was running as root, but running as user gave the same output.

**Comment by theyosh** [comment]
Ok, uploaded a new package to openrepos. It is missing a dependency. I hope that with the new version 3-3 this dependency will be installed (dbus-python3)

**Comment by eson57** [comment]
dbus-python3 seems to be missing in repo.

![skarmbild_20161106_002](https://cloud.githubusercontent.com/assets/2996154/20037806/38346c86-a428-11e6-8d02-5f61761efbb0.png)

**Comment by theyosh** [comment]
hmm, this is strange. Because it is known. Could be that the packages are outdated? Not sure how that happens, but try:

`pkcon refresh` as nemo or `zypper refresh` as root

Else I have to try to make it working on Python 2, but thought that Python 3 was/is default on Jolla

**Comment by eson57** [comment]
Great! After clean reinstall, it is finally working. Thanks!  :+1:

**Comment by theyosh** [comment]
hmm, so how to fix the outdated packages.....?

**Comment by theyosh** [comment]
But cool that it is working. And it should be in Swedish also now

**Comment by eson57** [comment]
Yes, Swedish is working fine, and looking good. :)
