### ISSUE TITLE
How to handle e.g. eduroam networks?

### ISSUE THREAD

**Issue by bonanza123** [theyosh/WiFiKilL3r#4]
What is the correct way to handle e.g. eduroam networks where a configured CA-certificate is given? Should the CA-certificate pinning be sufficient to ensure safety in this case? Would it then make sense to have some kind of wildcard options which accepts any bssid? Would it be possible to auto-detect such a configuration?

**Comment by theyosh** [comment]
Hi, I am unfamiliar with eduroam networks. And I do not work with CA-certificates. So I have no clue.
