### ISSUE TITLE
configured Wifi not recongnized

### ISSUE THREAD

**Issue by fuchsmich** [theyosh/WiFiKilL3r#5]
While the app works like expected with the wifi at work, at home it doenst. I configured the network (also check if it is present in valid_networks), but the app keeps shutting down the wifi.

How can I help debugging this?

**Comment by theyosh** [comment]
Hmm there is not a lot of debugging yet, but a start is to edit the file:

/usr/share/WiFiKilL3r/qml/python/WiFiKilL3r.py

And around line 14 there is Debug = False. Change that to Debug = True and let it run.

It will produce more logging at the logging file: /home/nemo/.WiFiKilL3r/WiFiKilL3r.log

Maybe it will show there what it does and why it disconnects.

**Comment by zwieberl** [comment]
I have the same problem. I edited the file you mentioned, but got only "Wifi not in trusted networks. Disconnecting". So I added an output to show what its comparing it to. I got this:

```
Feb 06 09:13:16 Sailfish bash[23248]: INFO:WiFiKilL3r:Start cron run
Feb 06 09:13:16 Sailfish bash[23248]: DEBUG:WiFiKilL3r:Wifi is enabled
Feb 06 09:13:16 Sailfish bash[23248]: DEBUG:WiFiKilL3r:Connected to WiFi network: na(XX:XX:XX:XX:XX:XX)
Feb 06 09:13:16 Sailfish bash[23248]: DEBUG:WiFiKilL3r:Loaded 1 trusted networks: name_of_my_wifi(XX:XX:XX:XX:XX:XX)
Feb 06 09:13:16 Sailfish bash[23248]: DEBUG:WiFiKilL3r:na(XX:XX:XX:XX:XX:XX) WiFi network is not trusted. Shutting down WiFi
Feb 06 09:13:16 Sailfish bash[23248]: DEBUG:WiFiKilL3r:Wifi is enabled
Feb 06 09:13:16 Sailfish bash[23248]: DEBUG:WiFiKilL3r:Disable wifi
```
(Note: I edited out my actual SSID and replaced it with a placeholder)

Somehow, the name of the Wifi to compare it to is truncated to the first 2 characters.
Thus the comparison failed and the wifi gets disconnected.

**Comment by zwieberl** [comment]
Something is wrong with the regex, but I couldn't figure out what. So I replaced the whole function with non-regex-parsing:

```
 def get_wifi_status():
   current_wifi = ''
   try:
-    current_wifi =  str(subprocess.check_output('/usr/sbin/iw dev wlan0 link', shell=True).strip())
-    regex = re.compile(r'Connected to (?P<mac>[^ ]+).*SSID: (?P<ssid>[^\\n]+)')
-    data = re.search(regex, current_wifi)
-    if data is not None:
-      current_wifi = data.group('ssid') + '(' + data.group('mac') + ')'
+    mac = ''
+    ssid = ''
+    current_wifi = subprocess.check_output('/usr/sbin/iw dev wlan0 link', shell=True).decode()
+    for line in current_wifi.splitlines():
+        if "Connected to " in line:
+            mac = line.strip().split()[2]
+        if "SSID: " in line:
+            ssid = line.strip()[5:].strip()
+
+    if mac != "" and ssid != "":
+      current_wifi = ssid + '(' + mac + ')'
   except:
     current_wifi = ''
```

Now it works.

**Comment by theyosh** [comment]
Sorry, totally missed this. I have updated my code slightly differently. But I see the issue. Should work now.

**Comment by zwieberl** [comment]
Just out of curiosity: Could you push your changes to github? I would like to see the final version (without starting to dig on the phone itself)

**Comment by theyosh** [comment]
Yes! just did :)

https://github.com/theyosh/WiFiKilL3r/blob/master/qml/python/WiFiKilL3r.py#L108

**Comment by zwieberl** [comment]
Cool, thanks!
Just tested it with my original wifi. The new version works!
