### ISSUE TITLE
Translation string to long

### ISSUE THREAD

**Issue by eson57** [theyosh/WiFiKilL3r#8]
Hi,
Can you make the string `Here you can enable or disable settings.` a two liner? Its a bit to long (in Swedish) and don fit the screen on my X.
`<location filename="../qml/pages/SettingsPage.qml" line="25"/>`

Thanks.

**Comment by theyosh** [comment]
Hi, thanks for the translation. Really cool.

So I added text wrapping to the label, so it should wrap and stay inside the screen dimensions.

**Comment by eson57** [comment]
Thanks!
